Feature/google api calender
saunah/saunah-backend pull request #51
Opened 2022-05-03 14:59 UTC by Utschu

## Summary
Create an interface to communicate with the google API  Service
## Related Issues

- Closes #39
- Fixes #

## Definition of Done

- User story
  - [ ] All stated conditions fulfilled
- Code
  - [ ] No more code needed
  - [ ] No known bugs
- Clean Code
  - [ ] JavaDoc has been added
  - [ ] API documentation has been added via annotations (if applicable)
  - [ ] No unavoidable code smells
- Testing
  - [ ] All existing tests pass
  - [ ] New unit tests created according to [CONTRIBUTING.md](./CONTRIBUTING.md#-testing-strategy)
  - [ ] New unit tests pass
- SonarCloud
  - [ ] Quality gate passed
- Compatibility to frontend
  - [ ] Compatibility to staging-frontend verified (running frontend locally in Docker container with image matching the deployed image on staging)

2022-05-03 17:31 UTC, TG134516 commented on src/test/java/ch/saunah/saunahbackend/service/GoogleCalendarServiceTest.java
> +        System.out.println(events);
Remove system.out.println if they are no longer necessary

2022-05-03 17:33 UTC, TG134516 submitted a review, later dismissed
small change required and solve merge conflict.

2022-05-03 20:49 UTC, simonschuhmacher requested changes
Looks good to me 🙂
I just cleaned up a bit for the gradle dependencies (not directly related to this pr) and removed stuff we no longer needed and updated some dependencies to the latest version.

Except of the print statement marcel mentioned, I think it's nice.

2022-05-04 21:15 UTC, simonschuhmacher approved these changes
Nice

2022-05-04 21:18 UTC, merged