Feature/sauna booking mail
saunah/saunah-backend pull request #82
Opened 2022-05-14 17:54 UTC by lalicde1

## Summary

Updated Booking types, added prices to booking and now emails are sent upon booking, approval and cancelation.

## Related Issues

- Closes #77 
- Closes #57 
- Closes #74 

## Definition of Done

- User story
  - [ ] All stated conditions fulfilled
- Code
  - [ ] No more code needed
  - [ ] No known bugs
- Clean Code
  - [ ] JavaDoc has been added
  - [ ] API documentation has been added via annotations (if applicable)
  - [ ] No unavoidable code smells
- Testing
  - [ ] All existing tests pass
  - [ ] New unit tests created according to [CONTRIBUTING.md](./CONTRIBUTING.md#-testing-strategy)
  - [ ] New unit tests pass
- SonarCloud
  - [ ] Quality gate passed
- Compatibility to frontend
  - [ ] Compatibility to staging-frontend verified (running frontend locally in Docker container with image matching the deployed image on staging)

2022-05-15 20:38 UTC, triumphvalley requested changes, later dismissed
@lalicde1 I saw that you changed the washService to be a number, like described in the issue. This is actually a mistake, please change it back to a boolean. A user can only request one washService per booking. Also described here: https://github.com/saunah/saunah-backend/issues/74#issuecomment-1127022126

2022-05-16 10:46 UTC, triumphvalley commented on src/main/java/ch/saunah/saunahbackend/controller/BookingController.java
> +    @PutMapping(path = "bookings/{id}/edit")
Just use `/bookings/{id}`. The `PUT` request indicates that it is an editing actoin.

2022-05-17 11:30 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/SaunahBackendApplication.java
> +                "/bookings/{id}"
user can edit the current booking, he should nbot be able to

2022-05-17 11:34 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/SaunahBackendApplication.java
> +                "/bookings/{id}"
only admin can cancel the booking, user should also be able to

2022-05-17 11:38 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/controller/BookingController.java
> +        mailService.sendUserApprovedBookingMail(userService.getUser(booking.getUserId()).getEmail(), booking, booking.getBookingPrice(), booking.getBookingSauna());
cant you just pass booking? because it contains all the data

2022-05-17 11:38 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/controller/BookingController.java
> +        mailService.sendUserCanceledBookingMail(userService.getUser(booking.getUserId()).getEmail(), booking, booking.getBookingPrice(), booking.getBookingSauna());
cant you just pass booking? because it contains all the data

2022-05-17 11:41 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/dto/BookingResponse.java
>      private String googleEventID;
remove google event id from response

2022-05-17 11:42 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/dto/BookingResponse.java
> +    private BookingSauna bookingSauna;
maybe return just id's of those two

2022-05-17 11:47 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/dto/BookingPriceResponse.java
> +import ch.saunah.saunahbackend.model.Booking;
remove unused import

2022-05-17 11:48 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/dto/BookingSaunaResponse.java
> +import ch.saunah.saunahbackend.model.Booking;
remove unused import

2022-05-17 11:49 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/model/BookingPrice.java
> +public class BookingPrice implements Serializable {
serializable entfernen, dieses problem wird gefixt, wenn man ind der booking reponse nicht mehr das objekt weiter schickt -> siehe kommentar nur id's schicken

2022-05-17 11:49 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/model/BookingSauna.java
> +public class BookingSauna implements Serializable {
serializable entfernen, dieses problem wird gefixt, wenn man ind der booking reponse nicht mehr das objekt weiter schickt -> siehe kommentar nur id's schicken

2022-05-17 11:51 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/repository/BookingSaunaRepository.java
> +    BookingSauna findByBookingId(int saunaId);
remove unused method

2022-05-17 11:53 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/BookingService.java
> +        booking.setBookingSauna(bookingSauna);
only set ids

2022-05-17 11:55 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/BookingService.java
> +    private BookingPrice createBookingPrice(BookingBody bookingBody, Booking id) {
remove unused id parameter

2022-05-17 11:55 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/BookingService.java
> +    private BookingSauna createBookingSauna(BookingBody bookingBody, Booking id) {
remove unused id parameter

2022-05-17 11:56 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/BookingService.java
> +        return bookingRepository.save(editBooking);
validate bookingbody data, same as in addBooking -> create a validate method

2022-05-17 11:57 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/BookingService.java
> +        return bookingRepository.save(editBooking);
now a user can put in start dates before the current one which is not logical, and more...

2022-05-17 11:58 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/BookingService.java
> +        BookingSauna bookingSauna = bookingSaunaRepository.findById(id).orElse(null);
get booking sauna by booking id and not just by id

2022-05-17 11:58 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/BookingService.java
> +        BookingPrice bookingPrice = bookingPriceRepository.findById(id).orElse(null);
get booking sauna by booking id and not just by id

2022-05-17 12:02 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/controller/BookingController.java
> +        BookingSauna bookingSauna = bookingService.getBookingSauna(id);
pass bookingPriceId from booking, id is not right when calling booking price because it can differ from id

2022-05-17 12:04 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/MailService.java
> +    private void messageUserSetup(String email, String mailText, Booking booking, BookingPrice bookingPrice, BookingSauna bookingSauna) {
method name doesnt say anything what the method does

2022-05-17 12:06 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/MailService.java
> +        }
i would change, that this method only sends to the user which was passed in the method argument. I would use the for loop in the other class where this method is called.

2022-05-17 12:07 UTC, cabernin commented on src/main/java/ch/saunah/saunahbackend/service/MailService.java
> +    private String bookingInfo(Booking booking, BookingPrice bookingPrice, BookingSauna bookingSauna) {
change method name to generateBookingInfoMessage

2022-05-17 12:09 UTC, cabernin requested changes
good job @dejeux. Not everyone is perfect, unless your name is perfect 😏. As a wise man once said: "Success is not final, failure is not fatal: it is the courage to continue that counts."

2022-05-17 12:30 UTC, lalicde1 commented
stfu @cabernin

2022-05-17 14:34 UTC, cabernin approved these changes
![output-onlinegiftools-min (2)](https://user-images.githubusercontent.com/80694748/168837126-db0baa85-fe74-4cdb-89ec-94c629bd8346.gif)

2022-05-17 14:35 UTC, merged